title: I'm JeongJoo
description: >-
  Full-Stack Developer
url: "https://givej.github.io"
github: giveJ
email: anjungju09@gmail.com
google_analytics: <anjungju09>

exclude: [README.md, Gemfile, Gemfile.lock]

comments:
  enabled: true
  repo: ChemistryX/hyde-comments
  issue-term: pathname

collections:
  pages:
    output: true
  projects:
    output: true
  tags:
    output: true

defaults:
  - scope:
      type: pages
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
      permalink: /blog/:title
  - scope:
      type: projects
    values:
      layout: project
      permalink: /projects/:title
  - scope:
      type: tags
    values:
      layout: tag
      permalink: /tags/:title
